spring.application.name=ProiectSCD

spring.datasource.url=jdbc:mysql://localhost:3306/socialmedia?createDatabaseIfNotExist=True
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.databse-platform=org.hibernate.dialect.MysQL8Dialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alexandudobrovolschi@gmail.com
spring.mail.password=zvrb agnh sepm ftvo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.hibernate.ddl-auto=update
server.port=8083
